name: LWJGL Build

on:
  push:
    branches:
      - master

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_PARAMS: --acl public-read --cache-control "public,must-revalidate,proxy-revalidate,max-age=0"
  OPUS_PARAMS: -DOPUS_INSTALL_PKG_CONFIG_MODULE=OFF -DOPUS_INSTALL_CMAKE_CONFIG_MODULE=OFF -DOPUS_HARDENING=OFF -DOPUS_STACK_PROTECTOR=OFF -DOPUS_BUILD_SHARED_LIBRARY=ON -DOPUS_CUSTOM_MODES=ON
  OPUS_CONFIG_PARAMS: --disable-extra-programs --disable-doc --disable-hardening --disable-stack-protector --enable-custom-modes

jobs:
  linux:
    name: Linux
    runs-on: ${{matrix.runner}}
    strategy:
      fail-fast: false
      matrix:
        ARCH: [x64, arm32, arm64, mips64]
        include:
          # -----
          - ARCH: x64
            runner: ubuntu-16.04
            PACKAGES: gcc-4.8
            CC: CC=gcc-4.8 LDFLAGS="-Wl,--wrap,memcpy"
            HOST: x86_64-pc-linux-gnu
            CMAKE_PARAMS: -DCMAKE_SHARED_LINKER_FLAGS=-Wl,--wrap,memcpy
            STRIP: strip
          # -----
          - ARCH: arm32
            runner: ubuntu-16.04
            PACKAGES: gcc-4.8-arm-linux-gnueabihf libc6-dev-armhf-cross
            CC: CC=arm-linux-gnueabihf-gcc-4.8
            HOST: arm-unknown-linux-gnueabihf
            CMAKE_PARAMS: -DCMAKE_TOOLCHAIN_FILE=../XCompile-lwjgl.cmake -DSYSTEM_NAME=Linux -DSYSTEM_PROCESSOR=arm
            STRIP: arm-linux-gnueabihf-strip
          # -----
          - ARCH: arm64
            runner: ubuntu-16.04
            # neon code compilation bugged on 4.8
            PACKAGES: gcc-5-aarch64-linux-gnu libc6-dev-arm64-cross
            CC: CC=aarch64-linux-gnu-gcc-5
            HOST: aarch64-unknown-linux-gnu
            CMAKE_PARAMS: -DCMAKE_TOOLCHAIN_FILE=../XCompile-lwjgl.cmake -DSYSTEM_NAME=Linux -DSYSTEM_PROCESSOR=aarch64
            STRIP: aarch64-linux-gnu-strip
          # -----
          - ARCH: mips64
            runner: ubuntu-16.04
            PACKAGES: gcc-5-mips64el-linux-gnuabi64 libc6-dev-mips64el-cross
            CC: CC=mips64el-linux-gnuabi64-gcc-5
            HOST: mips64el-unknown-linux-gnu
            CMAKE_PARAMS: -DCMAKE_TOOLCHAIN_FILE=../XCompile-lwjgl.cmake -DSYSTEM_NAME=Linux -DSYSTEM_PROCESSOR=mips64
            STRIP: mips64el-linux-gnuabi64-strip
    env:
      LWJGL_ARCH: ${{matrix.ARCH}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - run: sudo apt-get -yq install ${{matrix.PACKAGES}}
        name: Install dependencies
      - run: |
          ./autogen.sh
          ${{matrix.CC}} ./configure ${{env.OPUS_CONFIG_PARAMS}} --host=${{matrix.HOST}}
        name: Configure build
      - run: |
          make
          ${{matrix.STRIP}} .libs/libopus.so
        name: Build
      - run: aws s3 cp .libs/libopus.so s3://build.lwjgl.org/nightly/linux/${{matrix.ARCH}}/ $S3_PARAMS
        name: Upload artifact
      - run: |
          git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > libopus.so.git
          aws s3 cp libopus.so.git s3://build.lwjgl.org/nightly/linux/${{matrix.ARCH}}/ $S3_PARAMS
        name: Upload git revision

  macos:
    name: macOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ARCH: [x64, arm64]
        include:
          - ARCH: x64
            CC: CFLAGS="-O2 -mmacosx-version-min=10.9" LDFLAGS=-mmacosx-version-min=10.9
            HOST: x86_64
            CMAKE_PARAMS: -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9
          - ARCH: arm64
            CC: SDKROOT=$(xcrun -sdk macosx11.1 --show-sdk-path) MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx11.1 --show-sdk-platform-version) CFLAGS="-O2 -target aarch64-apple-darwin -arch arm64 -mmacosx-version-min=11.0" LDFLAGS="-target aarch64-apple-darwin -arch arm64 -mmacosx-version-min=11.0"
            HOST: aarch64
            CMAKE_PARAMS: -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_TOOLCHAIN_FILE=../XCompile-lwjgl.cmake -DSYSTEM_NAME=Darwin -DSYSTEM_PROCESSOR=aarch64
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - run: brew install automake
        name: Install dependencies
      - run: |
          ./autogen.sh
          ${{matrix.CC}} ./configure ${{env.OPUS_CONFIG_PARAMS}} --target ${{matrix.ARCH}}-apple-darwin20 --host=${{matrix.HOST}}-apple-darwin20
        name: Configure build
      - run: |
          ${{matrix.CC}} make
          strip -u -r .libs/libopus.dylib
        name: Build
      - run: aws s3 cp .libs/libopus.dylib s3://build.lwjgl.org/nightly/macosx/${{matrix.ARCH}}/ $S3_PARAMS
        name: Upload artifact
      - run: |
          git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > libopus.dylib.git
          aws s3 cp libopus.dylib.git s3://build.lwjgl.org/nightly/macosx/${{matrix.ARCH}}/ $S3_PARAMS
        name: Upload git revision

  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ARCH: [x86, x64, arm64]
        include:
          - ARCH: x86
            PLATFORM: Win32
          - ARCH: x64
            PLATFORM: x64
          - ARCH: arm64
            PLATFORM: ARM64
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 16 2019" -A ${{matrix.PLATFORM}} ${{env.OPUS_PARAMS}} ..
        shell: cmd
        name: Configure build
      - run: |
          cd build
          cmake --build . --config Release
        shell: cmd
        name: Build
      - run: aws s3 cp build\Release\opus.dll s3://build.lwjgl.org/nightly/windows/${{matrix.ARCH}}/ ${{env.S3_PARAMS}}
        shell: cmd
        name: Upload artifact
      - run: |
          git log --first-parent --pretty=format:%%H HEAD~2..HEAD~1 > opus.dll.git
          aws s3 cp opus.dll.git s3://build.lwjgl.org/nightly/windows/${{matrix.ARCH}}/ ${{env.S3_PARAMS}}
        shell: cmd
        name: Upload git revision

